services:
  backend:
    build:
      context: ./backend
    ports:
      - "3005:3005"
    env_file: ./backend/.env

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "5173:80"
    depends_on: [backend]
    env_file: ./frontend/.env.local
